spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: sys as sysdba
    password: Oradoc_db1
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    user: sys as sysdba
    password: Oradoc_db1
#    change-log: classpath:/com/internship/epayment/config/changelog/db.changelog-master.xml
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: 8082