spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1531:ORCLCDB
    username: sys as sysdba
    password: Oradoc_db1
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.xml
server:
  port: 8082